workflows:
  android-release:
    name: Nid Poule APK
    environment:
      flutter: 3.41.1

    scripts:
      - flutter clean
      - flutter pub get

      # Générer Android
      - flutter create --platforms android .

      # Vérifier que le dossier existe
      - ls -la

      # Ajouter permissions GPS dans le manifest généré
      - |
        sed -i '/<manifest/a\
        <uses-permission android:name="android.permission.INTERNET"/>\
        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>\
        <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>\
        <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>\
        <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>\
        <uses-permission android:name="android.permission.CAMERA"/>' android/app/src/main/AndroidManifest.xml

      # Build APK
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk